services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SECRET_KEY=django-insecure-$s6x0!70=y=u*p73nxe9*h&vj#ixmamc4m8fvrtjr8-feuh$in
      - DEBUG=1

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: 'db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data:

    